// <auto-generated />
using System;
using DuckyTalk.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DuckyTalk.Migrations
{
    [DbContext(typeof(DuckyTalkContext))]
    partial class DuckyTalkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DuckyTalk.Database.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Description = "Rock music",
                            Name = "Music"
                        },
                        new
                        {
                            InterestId = 2,
                            Description = "Comedy",
                            Name = "Movies"
                        });
                });

            modelBuilder.Entity("DuckyTalk.Database.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnologyId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DuckyTalk.Database.Technology", b =>
                {
                    b.Property<int>("TechnologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TechnologyId");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            TechnologyId = 1,
                            Description = "",
                            IsDeleted = false,
                            Name = "NaN"
                        },
                        new
                        {
                            TechnologyId = 2,
                            Description = "SQL is a standard language for accessing and manipulating databases.",
                            IsDeleted = false,
                            Name = "SQL"
                        },
                        new
                        {
                            TechnologyId = 3,
                            Description = "Java is an object-oriented programming language that produces software for multiple platforms.",
                            IsDeleted = false,
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("DuckyTalk.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDate = new DateTime(1998, 11, 4, 14, 28, 58, 693, DateTimeKind.Local),
                            Email = "anisa.mehremic@edu.fit.ba",
                            FirstName = "Anisa",
                            LastName = "Mehremic",
                            PasswordHash = "+WQk9mVupe+VOTeMI1a8PsyMmR0=",
                            PasswordSalt = "cPYUsauMRpahKHypOM3BIA==",
                            Username = "anisam"
                        },
                        new
                        {
                            UserId = 2,
                            BirthDate = new DateTime(1998, 12, 21, 11, 55, 58, 693, DateTimeKind.Local),
                            Email = "lejla.mujakic@edu.fit.ba",
                            FirstName = "Lejla",
                            LastName = "Mujakic",
                            PasswordHash = "+WQk9mVupe+VOTeMI1a8PsyMmR0=",
                            PasswordSalt = "cPYUsauMRpahKHypOM3BIA==",
                            Username = "lejlam"
                        });
                });

            modelBuilder.Entity("DuckyTalk.Database.UserBreakReminder", b =>
                {
                    b.Property<int>("UserBreakReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserBreakReminderId");

                    b.ToTable("UserBreakReminders");
                });

            modelBuilder.Entity("DuckyTalk.Database.UserInterest", b =>
                {
                    b.Property<int>("UserInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserInterestId");

                    b.ToTable("UserInterests");

                    b.HasData(
                        new
                        {
                            UserInterestId = 1,
                            InterestId = 1,
                            IsActive = false,
                            UserId = 1
                        },
                        new
                        {
                            UserInterestId = 2,
                            InterestId = 1,
                            IsActive = true,
                            UserId = 2
                        },
                        new
                        {
                            UserInterestId = 3,
                            InterestId = 2,
                            IsActive = true,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DuckyTalk.Database.UserMessage", b =>
                {
                    b.Property<int>("UserMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeShowed")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserMessageId");

                    b.ToTable("UserMessages");

                    b.HasData(
                        new
                        {
                            UserMessageId = 1,
                            MessageId = 1,
                            TimeShowed = new DateTime(2022, 5, 12, 14, 28, 58, 693, DateTimeKind.Local),
                            UserId = 1
                        },
                        new
                        {
                            UserMessageId = 2,
                            MessageId = 2,
                            TimeShowed = new DateTime(2022, 5, 12, 15, 28, 58, 693, DateTimeKind.Local),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DuckyTalk.Database.UserTechnology", b =>
                {
                    b.Property<int>("UserTechnologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserTechnologyId");

                    b.ToTable("UserTechnologies");

                    b.HasData(
                        new
                        {
                            UserTechnologyId = 1,
                            IsDeleted = false,
                            TechnologyId = 1,
                            UserId = 1
                        },
                        new
                        {
                            UserTechnologyId = 2,
                            IsDeleted = false,
                            TechnologyId = 1,
                            UserId = 2
                        },
                        new
                        {
                            UserTechnologyId = 3,
                            IsDeleted = false,
                            TechnologyId = 2,
                            UserId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
