version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.1.0-full
    ports:
      - 5005:5005
    expose:
        - 5005
    volumes:
      - ./:/app
    command:
      - run
  botactions:
    build:
      context: .
      dockerfile: ActionsDockerfile
    expose:
        - 5055